sudo: true
git:
  depth: 3
addons:
  postgresql: '9.4'
language: python
python:
- '3.5'
branches:
  only:
  - dev
  - master
env:
  global:
  - DJANGO_SETTINGS_MODULE=config.settings.test
  - DATABASE_URL=postgres://postgres@localhost:5432
install:
- pip install -r requirements/test.txt
- pip install coveralls
script:
- coverage run -m py.test
after_script:
- coveralls
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: "z54+2x9oAcBgtfMs1iJOK43ORgE/ZLyaPfZKfSvo8ySCc4xWnNUwsefuWxAFXEDLDuMzZoCwQdv/sJB3rt/ij5gVUFntFi9KNIfgwgJR8KaB+r/Da/ywHOwu3ghNmwIlEXk/n9fhfFjrqltihYpmxpzksxu0VAPrv1812LbF9CzKdPQocFYWsrhsdlQvtUExzxIw9z8/gAoZ7yGJpmHjCnGfEhlI9bFbDiHE9m/5UHlJwM0fu+nv4dEtc2WRHR1vZts06Za7ixk4MK/5kOTTvAuVu6rGrivZ2u2rdsmcPkgu8JGRiHNJMeVvdhiglS/+hWNZi6sTDhdEMAyHOmgDtSkq5PaR0W9LOGe1UEafQuHlVmwFUmxpiNHVGyqXBr44mmtkXr/70DU6DKjXUePzchVGbf28dG4QOQBy7ZHwAVGsMZQFBa6uYQgwFEim6fvOu3VJeX92wsb6SnYkI+hIGqRUIV6elRAR0BRFjqh/n/diCgBL6C+rAHKmKrPQu7cKKcUnd6Yi2xVC0TPvWagdOxcj+dS25vv6/graU9aXDElp2K5WUPxlN22EVyulawR1paPBU3dt9Gk1bXI3F7xx5XhcnzBURYBMQa95ACPbjaA5ZoK//tGBAEDB9E2Q5b84TZkz/bafgo4eFVaXmOUM9rypH26MtOEwRhpvvpgyOcA="
  app:
    master: renty
    dev: renty-dev
  run:
  - python ./manage.py migrate
  - restart
