sudo: true
git:
  depth: 3
addons:
  postgresql: '9.4'
language: python
python:
- '3.5'
branches:
  only:
  - dev
  - master
env:
  global:
  - DJANGO_SETTINGS_MODULE=config.settings.test
  - DATABASE_URL=postgres://postgres@localhost:5432
install:
- pip install -r requirements/test.txt
- pip install coveralls
script:
- coverage run -m py.test
after_script:
- coveralls
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: "e3pW/LaTyMpkkM+Spvqk+xAGFSLZYjsysqd+a/1reNc3T1gOkjJd8E9AE3EO0hqhpEUMYIhbO68j9RBIVLOTw/D6eHBr7yv4sVNTu1EoqDnA9P3trV19wlWiwQ5vGOgvkrWUPG2gvcdhvVHNUC4a+Wq5EnAd25g1h9GAOUg8EqApU+jVLWnwvfx4FSE6aOylR49qNsKSML/mAc+G9A47aA4nhFFJJ+TnnCpcKjVAB2QmoborZNoo10XZCJZ7o9far1Xigh2pW7dts0RGRq0GumPTMII6CjK9xy0XPHCKQqYEew/d6QztnW091rzQa95bcSSaxfQdkW1sPysnDJcu84BEPDjLLyQzunF8ekfWFGd+leh6oAgFRo/eT5t4q3VrP9m0dyw/xA0aglSFsazgAqRF1jwSWfJGUmKNqbToU3qOe7WQQu07/+7JKZkCWv4pkvIbHMvFpPs1N+5YofgoHfxxIuH1FPv63Pb5Px15TnZyMWH4i7rUTtHWdr8n90K6dxmcmGn0GVtuzXiuvOch2gzE63QdI1VTKdve9tCToxUHBpZflFlAh1sGTZ/5AvTzGtizqD3rluW9jkxVezAI0Ta5v288sG9fIu4MFH2mfFfAauyigVjMO/pNSbC8dhNl5tLuS+hL6S0Xil0iKbVY5yCOk0noqbTH6f5wpSd2Er8="
  app:
    master: renty
    dev: renty-dev
  run:
  - python ./manage.py migrate
  - restart
