sudo: true

addons:
  postgresql: "9.4"
env:
 global:
  - DJANGO_SETTINGS_MODULE=config.settings.test
  - DATABASE_URL=postgres://postgres@localhost:5432/test_db

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
  - sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev libwebp-dev
  - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
  - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
  - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm
install:
  - pip install -r requirements/test.txt
  - pip install coveralls
befores_script:
  - psql -c 'create database test_db;' -U postgres; fi

language: python
python:
- "3.5"

branches:
  only:
    - dev
    - master
script:
  - coverage run manage.py test
after_script:
  - coveralls
