sudo: true

addons:
  postgresql: "9.4"
env:
 global:
  - DJANGO_SETTINGS_MODULE=config.settings.test
  - DATABASE_URL=postgres://postgres@localhost:5432/test_db

install:
  - pip install -r requirements/test.txt
  - pip install coveralls

language: python
python:
- "3.5"

branches:
  only:
    - dev
    - master
script:
  - coverage run manage.py test
after_script:
  - coveralls
